apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: todo
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32050