apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: todo-app
spec:
  project: default
  source: argocd/applicationsets
    repoURL: https://github.com/gmrahul/k8s-todo-app.git
    targetRevision: main
    path: 
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: todo
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true  
    syncOptions:    
    - CreateNamespace=true 
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 3m
